name: Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
# jobs:
#     test:
#         runs-on: ubuntu-latest

#         services:
#             redis:
#                 image: redis
#                 ports:
#                     - 6379:6379
#             mongodb:
#                 image: mongo
#                 ports:
#                     - 27017:27017

#         steps:
#             - uses: actions/checkout@v2

#             - name: Set up Python
#               uses: actions/setup-python@v2
#               with:
#                   python-version: "3.9"

#             - name: Install dependencies
#               run: |
#                   python -m pip install --upgrade pip
#                   pip install -r requirements.txt
#                   pip install pytest pytest-asyncio pytest-cov

#             - name: Run tests
#               run: |
#                   pytest
#               env:
#                   REDIS_HOST: localhost
#                   REDIS_PORT: 6379
#                   MONGO_URI: mongodb://localhost:27017
#                   MONGO_DB: test_db

#             - name: Upload coverage reports
#               uses: codecov/codecov-action@v3
#               if: success()
